# Generated by Django 4.1.7 on 2023-03-07 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produitnc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitnc',
            name='id',
        ),
        migrations.AddField(
            model_name='produitnc',
            name='produit_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magasin.produit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produitnc',
            name='Duree_garantie',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCde', models.DateField(default=datetime.date.today, null=True)),
                ('totalCde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('produits', models.ManyToManyField(to='magasin.produit')),
            ],
        ),
    ]
