# Generated by Django 4.1.7 on 2023-04-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_remove_produitnc_id_produitnc_produit_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Fournisseur',
            new_name='fournisseur',
        ),
    ]
