# Generated by Django 4.1.7 on 2023-04-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img1.jpg', upload_to='profile_pics/'),
        ),
    ]
